swagger: '2.0'

info:
  version: 1.0.0
  title: godev2022desafio
  x-senior-domain: godev
  x-senior-domain-path: godev
  x-senior-service-path: godev2022desafio
  contact:
    name: Senior X Platform
    url: https://dev.senior.com.br
    email: seniorx-dev@senior.com.br

host: api.senior.com.br

basePath: /godev/godev2022desafio/

securityDefinitions:
   bearerAuth:
     type: apiKey
     in: header
     name: Authorization

produces:
  - application/json
consumes:
  - application/json

paths:
  
definitions:
  precriptionType:
    description: "Tipo de receita"
    type: string
    enum:
      - YELLOW
      - BLUE
      - WHITE
    
  
  userNotificationKind:
    description: "User notification kind."
    type: string
    enum:
      - Operational
      - Management
      - News
    
  
  userNotificationPriority:
    description: "User notification priority."
    type: string
    enum:
      - Error
      - Alert
      - None
    
  
  eventEmailFormat:
    description: "Format of the email"
    type: string
    enum:
      - HTML
      - PLAIN_TEXT
    
  
  fieldType:
    description: ""
    type: string
    enum:
      - BINARY
      - BOOLEAN
      - DATE
      - DATETIME
      - DOUBLE
      - ENUM
      - INTEGER
      - MONEY
      - STRING
      - TIME
    
  
  fileFormat:
    description: ""
    type: string
    enum:
      - CSV
      - FLAT
      - JSON
      - XML
    
  
  hookFunction:
    description: ""
    type: string
    enum:
      - BEFORE_PARSE
      - BEFORE_CONVERSION
      - ON_ERROR
      - VALIDATE
    
  
  eventType:
    description: ""
    type: string
    enum:
      - CHUNK
      - DOWNLOAD
      - ERROR
      - FINISH
      - START
    
  
  errorStrategy:
    description: ""
    type: string
    enum:
      - CALL_SCRIPT
      - IGNORE
      - STOP
    
  
  status:
    description: ""
    type: string
    enum:
      - DONE
      - DONE_WITH_ERRORS
      - DOWNLOADING
      - ERROR
      - NOT_STARTED
      - RUNNING
    
  
  errorType:
    description: ""
    type: string
    enum:
      - CONVERT_ERROR
      - SERVICE_ERROR
    
  patientResponse:
    description: "Retorno de usuario ativo"
    type: object
    required:
      - name
      - isAtivo
    properties:
      name:
        type: string
        description: "Nome do paciente"
      isAtivo:
        type: boolean
        description: "Status do paciente"
  
  patient:
    description: "Paciente"
    type: object
    required:
      - name
      - address
      - phone
    properties:
      id:
        type: string
        format: uuid
        description: "Id do paciente"
      name:
        type: string
        description: "Nome do paciente"
      cpf:
        type: string
        description: "CPF do paciente"
      address:
        type: string
        description: "Endereco Paciente"
      phone:
        type: integer
        format: int64
        description: "Telefone do paciente"
      responsibleDoctors:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/doctor'
        description: "Médico responsável pelo paciente"
      responsibleFamilyMembers:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/responsibleFamilyMember'
        description: "Familiar responsável pelo paciente"
      prescriptions:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/prescription'
        description: "Prescições médicas do paciente"
      isAtivo:
        type: boolean
        description: "Status do paciente"
        default: false
  
  doctor:
    description: "Médico"
    type: object
    required:
      - name
      - cpf
      - crmNumber
      - crmState
      - especiality
    properties:
      id:
        type: string
        format: uuid
        description: "Id do medico"
      name:
        type: string
        description: "Nome do medico"
      cpf:
        type: string
        description: "Cpf do medico"
      crmNumber:
        type: integer
        format: int64
        description: "CRM do medico"
      crmState:
        type: string
        description: "Estado do CRM do medico"
      especiality:
        type: string
        description: ""
      prescriptions:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/prescription'
        description: "Prescrições"
  
  prescription:
    description: "Prescricao Médica"
    type: object
    required:
      - drug
      - description
      - data
      - type
    properties:
      id:
        type: string
        format: uuid
        description: "Id da prescricao"
      drug:
        type: string
        description: "Medicamento"
      description:
        type: string
        description: "Descricao da prescricao"
      data:
        type: string
        format: date
        description: "Data da prescricao"
      doctorResponsible:
        type: object
        allOf:
         - $ref: '#/definitions/doctor'
        description: "Medico que prescreveu"
      type:
        type: string
        allOf:
        - $ref: '#/definitions/precriptionType'
        description: "Tipo de prescricao"
      statementOfReponsability:
        type: boolean
        description: "Termo de responsabildiade\n
          "
        default: false
      patient:
        type: object
        allOf:
         - $ref: '#/definitions/patient'
        description: "Paciente"
  
  responsibleFamilyMember:
    description: "Familiar Responsável"
    type: object
    required:
      - name
      - cpf
    properties:
      id:
        type: string
        format: uuid
        description: "Id do Familiar Responsável"
      name:
        type: string
        description: "Nome do Responsável"
      cpf:
        type: string
        description: "Cpf do responsável"
      kinship:
        type: string
        description: "Grau de parentesco"
  
  notifyUserEventPayload:
    description: "Represents a regular user event notification payload"
    discriminator: _discriminator
    type: object
    required:
      - notificationKind
      - notificationPriority
      - notificationSubject
      - notificationContent
      - sourceDomain
      - sourceService
      - destinationUser
      - _discriminator
    properties:
      notificationClass:
        type: string
        description: "Class of notification"
      notificationOrigin:
        type: string
        description: "Origin of notification. Free text. Optional."
      notificationKind:
        type: string
        allOf:
        - $ref: '#/definitions/userNotificationKind'
        description: "Notification kind."
      notificationPriority:
        type: string
        allOf:
        - $ref: '#/definitions/userNotificationPriority'
        description: "Notification priority."
      notificationSubject:
        type: string
        description: "Notification subject."
      notificationContent:
        type: string
        description: "Notification content."
      sourceDomain:
        type: string
        description: "Domain that generates the notification."
      sourceService:
        type: string
        description: "Service that generates the notification."
      destinationUser:
        type: string
        description: "Username of the destination user."
      link:
        type: string
        description: "Notification link"
      _discriminator:
        type: string
        description: ""
  
  emailNotifyUserEventPayload:
    description: "Represents an email notification payload"
    allOf:
    - $ref: '#/definitions/notifyUserEventPayload'
    - 
      type: object
      required:
        - from
      properties:
        from:
          type: string
          description: "Email sender address"
        sendTo:
          type: array
          items:
            type: string
          description: "Additional recipients to send the email to"
        format:
          type: string
          allOf:
          - $ref: '#/definitions/eventEmailFormat'
          description: "Email format"
  
  pushNotifyUserEventPayload:
    description: "Represents a push notification payload"
    allOf:
    - $ref: '#/definitions/notifyUserEventPayload'
    - 
      type: object
      required:
        - applicationId
      properties:
        applicationId:
          type: string
          description: "Apple/Google application id"
  
  blobReference:
    description: "Default blob reference type. Every service defines its own."
    type: object
    required:
      - targetObjectId
    properties:
      domainName:
        type: string
        description: "The domain the blob belongs to."
      serviceName:
        type: string
        description: "The service the blob belongs to."
      targetObjectId:
        type: string
        description: "The basic id of the blob."
      targetCopyId:
        type: string
        description: "The id of the blob copy."
  
  basicErrorPayload:
    description: "Default error payload type. Every service defines its own."
    type: object
    properties:
      message:
        type: string
        description: "The user-facing error message, if any."
      errorCode:
        type: string
        description: "The program-accessible (and service-specific) error code."
  
  importError:
    description: ""
    type: object
    required:
      - errorType
      - lineNumber
      - bean
      - message
      - exceptionClass
    properties:
      errorType:
        type: string
        allOf:
        - $ref: '#/definitions/errorType'
        description: ""
      lineNumber:
        type: integer
        format: int64
        description: ""
      bean:
        type: string
        description: ""
      message:
        type: string
        description: ""
      exceptionClass:
        type: string
        description: ""
  
  fielddto:
    description: ""
    type: object
    required:
      - id
      - name
      - fieldType
    properties:
      id:
        type: integer
        format: int64
        description: ""
      name:
        type: string
        description: ""
      fieldType:
        type: string
        allOf:
        - $ref: '#/definitions/fieldType'
        description: ""
      start:
        type: integer
        format: int64
        description: ""
      size:
        type: integer
        format: int64
        description: ""
      maskPattern:
        type: string
        description: ""
  
  hookdto:
    description: ""
    type: object
    required:
      - hookFunction
      - script
    properties:
      hookFunction:
        type: string
        allOf:
        - $ref: '#/definitions/hookFunction'
        description: ""
      script:
        type: string
        description: ""
  
  layoutdto:
    description: ""
    type: object
    required:
      - id
      - description
      - fileFormat
      - errorStrategy
      - skipLines
      - fields
    properties:
      id:
        type: integer
        format: int64
        description: ""
      description:
        type: string
        description: ""
      fileFormat:
        type: string
        allOf:
        - $ref: '#/definitions/fileFormat'
        description: ""
      errorStrategy:
        type: string
        allOf:
        - $ref: '#/definitions/errorStrategy'
        description: ""
      delimiter:
        type: string
        description: ""
      skipLines:
        type: integer
        format: int64
        description: ""
      fields:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/fielddto'
          minimum: 1
        description: ""
      hooks:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/hookdto'
        description: ""
  
  importReport:
    description: ""
    type: object
    required:
      - id
      - startTime
      - endTime
      - uri
      - beanClass
      - serviceClass
      - layout
      - sucessCount
      - errorsCount
      - filteredCount
      - skippedCount
    properties:
      id:
        type: string
        description: ""
      startTime:
        type: string
        format: date-time
        description: ""
      endTime:
        type: string
        format: date-time
        description: ""
      uri:
        type: string
        description: ""
      beanClass:
        type: string
        description: ""
      serviceClass:
        type: string
        description: ""
      layout:
        type: object
        allOf:
         - $ref: '#/definitions/layoutdto'
        description: ""
      sucessCount:
        type: integer
        format: int64
        description: ""
      errorsCount:
        type: integer
        format: int64
        description: ""
      filteredCount:
        type: integer
        format: int64
        description: ""
      skippedCount:
        type: integer
        format: int64
        description: ""
      importErrors:
        type: array
        items:
          type: object
          allOf:
           - $ref: '#/definitions/importError'
        description: ""
  
  exportEventStatus:
    description: ""
    type: object
    required:
      - importerId
      - eventType
      - recordCount
    properties:
      importerId:
        type: string
        description: ""
      eventType:
        type: string
        allOf:
        - $ref: '#/definitions/eventType'
        description: ""
      recordCount:
        type: integer
        format: int64
        description: ""
  
  importEventStatus:
    description: ""
    type: object
    required:
      - importerId
      - eventType
      - status
      - recordCount
    properties:
      importerId:
        type: string
        description: ""
      eventType:
        type: string
        allOf:
        - $ref: '#/definitions/eventType'
        description: ""
      status:
        type: string
        allOf:
        - $ref: '#/definitions/status'
        description: ""
      errorMessage:
        type: string
        description: ""
      recordCount:
        type: integer
        format: int64
        description: ""
      importReport:
        type: object
        allOf:
         - $ref: '#/definitions/importReport'
        description: ""
  
  exportConfig:
    description: ""
    type: object
    required:
      - uri
      - layout
      - async
      - errorStrategy
    properties:
      uri:
        type: string
        description: ""
      layout:
        type: object
        allOf:
         - $ref: '#/definitions/layoutdto'
        description: ""
      async:
        type: boolean
        description: ""
      errorStrategy:
        type: string
        description: ""
  
  importConfig:
    description: ""
    type: object
    required:
      - uri
      - layout
      - async
      - batchSize
      - errorStrategy
    properties:
      uri:
        type: string
        description: ""
      layout:
        type: object
        allOf:
         - $ref: '#/definitions/layoutdto'
        description: ""
      async:
        type: boolean
        description: ""
      batchSize:
        type: integer
        format: int64
        description: ""
      errorStrategy:
        type: string
        allOf:
        - $ref: '#/definitions/errorStrategy'
        description: ""
  
  dependency:
    description: "Represents a service dependency"
    type: object
    required:
      - domain
      - service
      - version
    properties:
      domain:
        type: string
        description: "Domain of the dependency service"
      service:
        type: string
        description: "Name of the dependency service"
      version:
        type: string
        description: "Version of the dependency service"
  
  genericError:
    properties:
      message:
        type: string
        description: Messaging describing the error.
      reason:
        type: string
        description: A symbolic code identifying the category of the reason of the error.
        enum:
          - BAD_REQUEST
          - UNAUTHORIZED
          - PAYMENT_REQUIRED
          - FORBIDDEN
          - OBJECT_NOT_FOUND
          - REQUEST_TIMEOUT
          - GONE
          - UNPROCESSABLE
          - INTERNAL_ERROR
          - NOT_IMPLEMENTED
          - SERVICE_UNAVAILABLE
          - INSUFFICIENT_STORAGE
