apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: godev2022
    domain: godev
    service: godev2022
  name: godev2022
  namespace: platform
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: godev2022
        domain: godev
        service: godev2022
      namespace: platform
    spec:
      containers:
      - env:
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: broker.host
        - name: BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: broker.port
        - name: BROKER_USER
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: broker.user
        - name: BROKER_PASS
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: broker.password
        - name: JAVA_OPTS
          value: -Xmx128m -XX:+UseG1GC -Xss256K -Dservicemodel.logger.br.com.senior=INFO
        image: seniorsa/godev2022:{$version}
        name: godev2022
  revisionHistoryLimit: 3
